# Configure Prometheus service

- name: Create Prometheus systemd service file
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
  notify:
    - Reload Systemd

- name: Enable and start Prometheus service
  systemd:
    name: prometheus
    enabled: yes
    state: started

# Configure Grafana service

- name: Create Grafana systemd service file
  template:
    src: "grafana.service.j2"
    dest: "/etc/systemd/system/grafana.service"
  notify:
    - Reload Systemd

- name: Enable and start Grafana service
  systemd:
    name: grafana
    enabled: yes
    state: started