SLACK_CHANNEL_NAME=build-status
ENVIRONMENT=prod
CODE_BASE_PATH=env/prod
ACTION_MESSAGE=Grafana and Prometheus deployment started
KEEP_APPROVAL_STAGE=true

INVENTORY=inventory/hosts
PLAYBOOK=play.yml
BRANCH=main
