#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/monitoring_role

- name: Reload Systemd
  systemd:
    daemon_reload: yes

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted  
  
- name: Restart Grafana
  systemd:
    name: grafana
    state: restarted